blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/soumiksarkar/hermes-notification-gateway/wiki
    about: Check our documentation for common questions and guides
  - name: 💬 Discussions
    url: https://github.com/soumiksarkar/hermes-notification-gateway/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/soumiksarkar/hermes-notification-gateway/security/advisories/new
    about: Report security vulnerabilities privately 